list(APPEND LIBAVUTIL_SOURCES adler32.c)
list(APPEND LIBAVUTIL_SOURCES aes.c)
list(APPEND LIBAVUTIL_SOURCES aes_ctr.c)
list(APPEND LIBAVUTIL_SOURCES ambient_viewing_environment.c)
list(APPEND LIBAVUTIL_SOURCES audio_fifo.c)
list(APPEND LIBAVUTIL_SOURCES avstring.c)
list(APPEND LIBAVUTIL_SOURCES avsscanf.c)
list(APPEND LIBAVUTIL_SOURCES base64.c)
list(APPEND LIBAVUTIL_SOURCES blowfish.c)
list(APPEND LIBAVUTIL_SOURCES bprint.c)
list(APPEND LIBAVUTIL_SOURCES buffer.c)
list(APPEND LIBAVUTIL_SOURCES cast5.c)
list(APPEND LIBAVUTIL_SOURCES camellia.c)
list(APPEND LIBAVUTIL_SOURCES channel_layout.c)
list(APPEND LIBAVUTIL_SOURCES container_fifo.c)
list(APPEND LIBAVUTIL_SOURCES cpu.c)
list(APPEND LIBAVUTIL_SOURCES crc.c)
list(APPEND LIBAVUTIL_SOURCES csp.c)
list(APPEND LIBAVUTIL_SOURCES des.c)
list(APPEND LIBAVUTIL_SOURCES detection_bbox.c)
list(APPEND LIBAVUTIL_SOURCES dict.c)
list(APPEND LIBAVUTIL_SOURCES display.c)
list(APPEND LIBAVUTIL_SOURCES dovi_meta.c)
list(APPEND LIBAVUTIL_SOURCES downmix_info.c)
list(APPEND LIBAVUTIL_SOURCES encryption_info.c)
list(APPEND LIBAVUTIL_SOURCES error.c)
list(APPEND LIBAVUTIL_SOURCES eval.c)
list(APPEND LIBAVUTIL_SOURCES executor.c)
list(APPEND LIBAVUTIL_SOURCES fifo.c)
list(APPEND LIBAVUTIL_SOURCES file.c)
list(APPEND LIBAVUTIL_SOURCES file_open.c)
list(APPEND LIBAVUTIL_SOURCES float_dsp.c)
list(APPEND LIBAVUTIL_SOURCES float_scalarproduct.c)
list(APPEND LIBAVUTIL_SOURCES film_grain_params.c)
list(APPEND LIBAVUTIL_SOURCES fixed_dsp.c)
list(APPEND LIBAVUTIL_SOURCES frame.c)
list(APPEND LIBAVUTIL_SOURCES hash.c)
list(APPEND LIBAVUTIL_SOURCES hdr_dynamic_metadata.c)
list(APPEND LIBAVUTIL_SOURCES hdr_dynamic_vivid_metadata.c)
list(APPEND LIBAVUTIL_SOURCES hmac.c)
list(APPEND LIBAVUTIL_SOURCES hwcontext.c)
list(APPEND LIBAVUTIL_SOURCES iamf.c)
list(APPEND LIBAVUTIL_SOURCES imgutils.c)
list(APPEND LIBAVUTIL_SOURCES integer.c)
list(APPEND LIBAVUTIL_SOURCES intmath.c)
list(APPEND LIBAVUTIL_SOURCES lfg.c)
list(APPEND LIBAVUTIL_SOURCES lls.c)
list(APPEND LIBAVUTIL_SOURCES log.c)
list(APPEND LIBAVUTIL_SOURCES log2_tab.c)
list(APPEND LIBAVUTIL_SOURCES lzo.c)
list(APPEND LIBAVUTIL_SOURCES mathematics.c)
list(APPEND LIBAVUTIL_SOURCES mastering_display_metadata.c)
list(APPEND LIBAVUTIL_SOURCES md5.c)
list(APPEND LIBAVUTIL_SOURCES mem.c)
list(APPEND LIBAVUTIL_SOURCES murmur3.c)
list(APPEND LIBAVUTIL_SOURCES opt.c)
list(APPEND LIBAVUTIL_SOURCES parseutils.c)
list(APPEND LIBAVUTIL_SOURCES pixdesc.c)
list(APPEND LIBAVUTIL_SOURCES pixelutils.c)
list(APPEND LIBAVUTIL_SOURCES random_seed.c)
list(APPEND LIBAVUTIL_SOURCES rational.c)
list(APPEND LIBAVUTIL_SOURCES refstruct.c)
list(APPEND LIBAVUTIL_SOURCES reverse.c)
list(APPEND LIBAVUTIL_SOURCES rc4.c)
list(APPEND LIBAVUTIL_SOURCES ripemd.c)
list(APPEND LIBAVUTIL_SOURCES samplefmt.c)
list(APPEND LIBAVUTIL_SOURCES side_data.c)
list(APPEND LIBAVUTIL_SOURCES sha.c)
list(APPEND LIBAVUTIL_SOURCES sha512.c)
list(APPEND LIBAVUTIL_SOURCES slicethread.c)
list(APPEND LIBAVUTIL_SOURCES spherical.c)
list(APPEND LIBAVUTIL_SOURCES stereo3d.c)
list(APPEND LIBAVUTIL_SOURCES tdrdi.c)
list(APPEND LIBAVUTIL_SOURCES threadmessage.c)
list(APPEND LIBAVUTIL_SOURCES time.c)
list(APPEND LIBAVUTIL_SOURCES timecode.c)
list(APPEND LIBAVUTIL_SOURCES timecode_internal.c)
list(APPEND LIBAVUTIL_SOURCES timestamp.c)
list(APPEND LIBAVUTIL_SOURCES tree.c)
list(APPEND LIBAVUTIL_SOURCES twofish.c)
list(APPEND LIBAVUTIL_SOURCES utils.c)
list(APPEND LIBAVUTIL_SOURCES xga_font_data.c)
list(APPEND LIBAVUTIL_SOURCES xtea.c)
list(APPEND LIBAVUTIL_SOURCES tea.c)
list(APPEND LIBAVUTIL_SOURCES tx.c)
list(APPEND LIBAVUTIL_SOURCES tx_float.c)
list(APPEND LIBAVUTIL_SOURCES tx_double.c)
list(APPEND LIBAVUTIL_SOURCES tx_int32.c)
list(APPEND LIBAVUTIL_SOURCES uuid.c)
list(APPEND LIBAVUTIL_SOURCES version.c)
list(APPEND LIBAVUTIL_SOURCES video_enc_params.c)
list(APPEND LIBAVUTIL_SOURCES video_hint.c)
if(CONFIG_CUDA)
    list(APPEND LIBAVUTIL_SOURCES hwcontext_cuda.c)
endif()
if(CONFIG_D3D11VA)
    list(APPEND LIBAVUTIL_SOURCES hwcontext_d3d11va.c)
endif()
if(CONFIG_D3D12VA)
    list(APPEND LIBAVUTIL_SOURCES hwcontext_d3d12va.c)
endif()
if(CONFIG_DXVA2)
    list(APPEND LIBAVUTIL_SOURCES hwcontext_dxva2.c)
endif()
if(CONFIG_AMF)
    list(APPEND LIBAVUTIL_SOURCES hwcontext_amf.c)
endif()
if(CONFIG_LIBDRM)
    list(APPEND LIBAVUTIL_SOURCES hwcontext_drm.c)
endif()
if(CONFIG_MACOS_KPERF)
    list(APPEND LIBAVUTIL_SOURCES macos_kperf.c)
endif()
if(CONFIG_MEDIACODEC)
    list(APPEND LIBAVUTIL_SOURCES hwcontext_mediacodec.c)
endif()
if(CONFIG_OHCODEC)
    list(APPEND LIBAVUTIL_SOURCES hwcontext_oh.c)
endif()
if(CONFIG_OPENCL)
    list(APPEND LIBAVUTIL_SOURCES hwcontext_opencl.c)
endif()
if(CONFIG_QSV)
    list(APPEND LIBAVUTIL_SOURCES hwcontext_qsv.c)
endif()
if(CONFIG_VAAPI)
    list(APPEND LIBAVUTIL_SOURCES hwcontext_vaapi.c)
endif()
if(CONFIG_VIDEOTOOLBOX)
    list(APPEND LIBAVUTIL_SOURCES hwcontext_videotoolbox.c)
endif()
if(CONFIG_VDPAU)
    list(APPEND LIBAVUTIL_SOURCES hwcontext_vdpau.c)
endif()
if(CONFIG_VULKAN)
    list(APPEND LIBAVUTIL_SOURCES hwcontext_vulkan.c)
    list(APPEND LIBAVUTIL_SOURCES vulkan.c)
endif()
if(NOT CONFIG_VULKAN)
    list(APPEND LIBAVUTIL_SOURCES hwcontext_stub.c)
endif()
# Warning: Unexpanded variable in file list: $(COMPAT_OBJS:%=../compat/%)
if(CONFIG_EXR_DECODER)
    list(APPEND LIBAVUTIL_SOURCES half2float.c)
    list(APPEND LIBAVUTIL_SOURCES float2half.c)
endif()
if(CONFIG_EXR_ENCODER)
    list(APPEND LIBAVUTIL_SOURCES float2half.c)
endif()
if(CONFIG_PHM_DECODER)
    list(APPEND LIBAVUTIL_SOURCES half2float.c)
endif()
if(CONFIG_PHM_ENCODER)
    list(APPEND LIBAVUTIL_SOURCES float2half.c)
endif()
if(CONFIG_SWSCALE)
    list(APPEND LIBAVUTIL_SOURCES half2float.c)
endif()
if(HAVE_GNU_WINDRES)
    list(APPEND LIBAVUTIL_SOURCES avutilres.c)
endif()
