# Sources for FFMPEG_SOURCES
if(CONFIG_FFMPEG)
    list(APPEND FFMPEG_SOURCES cmdutils.c)
    list(APPEND FFMPEG_SOURCES opt_common.c)
    list(APPEND FFMPEG_SOURCES ffmpeg.c)
    list(APPEND FFMPEG_SOURCES ffmpeg_dec.c)
    list(APPEND FFMPEG_SOURCES ffmpeg_demux.c)
    list(APPEND FFMPEG_SOURCES ffmpeg_enc.c)
    list(APPEND FFMPEG_SOURCES ffmpeg_filter.c)
    list(APPEND FFMPEG_SOURCES ffmpeg_hw.c)
    list(APPEND FFMPEG_SOURCES ffmpeg_mux.c)
    list(APPEND FFMPEG_SOURCES ffmpeg_mux_init.c)
    list(APPEND FFMPEG_SOURCES ffmpeg_opt.c)
    list(APPEND FFMPEG_SOURCES ffmpeg_sched.c)
    list(APPEND FFMPEG_SOURCES graph/graphprint.c)
    list(APPEND FFMPEG_SOURCES sync_queue.c)
    list(APPEND FFMPEG_SOURCES thread_queue.c)
    list(APPEND FFMPEG_SOURCES textformat/avtextformat.c)
    list(APPEND FFMPEG_SOURCES textformat/tf_compact.c)
    list(APPEND FFMPEG_SOURCES textformat/tf_default.c)
    list(APPEND FFMPEG_SOURCES textformat/tf_flat.c)
    list(APPEND FFMPEG_SOURCES textformat/tf_ini.c)
    list(APPEND FFMPEG_SOURCES textformat/tf_json.c)
    list(APPEND FFMPEG_SOURCES textformat/tf_mermaid.c)
    list(APPEND FFMPEG_SOURCES textformat/tf_xml.c)
    list(APPEND FFMPEG_SOURCES textformat/tw_avio.c)
    list(APPEND FFMPEG_SOURCES textformat/tw_buffer.c)
    list(APPEND FFMPEG_SOURCES textformat/tw_stdout.c)
    list(APPEND FFMPEG_SOURCES resources/resman.c)
endif()
# Sources for FFPROBE_SOURCES
if(CONFIG_FFPROBE)
    list(APPEND FFPROBE_SOURCES cmdutils.c)
    list(APPEND FFPROBE_SOURCES opt_common.c)
    list(APPEND FFPROBE_SOURCES ffprobe.c)
    list(APPEND FFPROBE_SOURCES textformat/avtextformat.c)
    list(APPEND FFPROBE_SOURCES textformat/tf_compact.c)
    list(APPEND FFPROBE_SOURCES textformat/tf_default.c)
    list(APPEND FFPROBE_SOURCES textformat/tf_flat.c)
    list(APPEND FFPROBE_SOURCES textformat/tf_ini.c)
    list(APPEND FFPROBE_SOURCES textformat/tf_json.c)
    list(APPEND FFPROBE_SOURCES textformat/tf_mermaid.c)
    list(APPEND FFPROBE_SOURCES textformat/tf_xml.c)
    list(APPEND FFPROBE_SOURCES textformat/tw_avio.c)
    list(APPEND FFPROBE_SOURCES textformat/tw_buffer.c)
    list(APPEND FFPROBE_SOURCES textformat/tw_stdout.c)
endif()
# Sources for FFPLAY_SOURCES
if(CONFIG_FFPLAY)
    list(APPEND FFPLAY_SOURCES cmdutils.c)
    list(APPEND FFPLAY_SOURCES opt_common.c)
    list(APPEND FFPLAY_SOURCES ffplay.c)
    list(APPEND FFPLAY_SOURCES ffplay_renderer.c)
endif()
# Sources for FFMPEG_SOURCES
if(CONFIG_FFMPEG)
    list(APPEND FFMPEG_SOURCES ${CMAKE_CURRENT_BINARY_DIR}/graph_html.c)
    list(APPEND FFMPEG_SOURCES ${CMAKE_CURRENT_BINARY_DIR}/graph_css.c)
endif()
